### PR TITLE
Add to_aiida_type serializer for calcjob inputs

### LINKED ISSUE #60: Automatically serialize inputs with `to_aiida_type`
Described in docs here: https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/usage.html?highlight=to_aiida_type#automatic-input-serialization

Would for example allow to pass input parameters as a simple Python `dict` instead of having it manually convert to AiiDA `Dict` node.

### PR DESCRIPTION
**Pull request by danielhollas**
Fixes #60

### CODE REVIEW

**Comment by danielhollas** [comment]
@sphuber I believe you added automatic serialization for calcfunctions. Would it make sense if `to_aiida_type` was a default serializer for WorkChains as well? It would be a lot user and developer friendlier.

**Comment by sphuber** [comment]
> @sphuber I believe you added automatic serialization for calcfunctions. 

Yes, I did indeed. Shipped with v2.1 I believe

> Would it make sense if `to_aiida_type` was a default serializer for WorkChains as well? It would be a lot user and developer friendlier.

Not sure if this would be possible. The spec is defined by the subclass, which calls the super _before_ it defines its own ports. So the base class won't get to intervene and automatically add the serializer to those ports. Not sure where to hook in to correct the port declarations.

Or we should override the `__setitem__` method of the `PortNamespace` class to set the serializer by default depending on the valid type. Could open an issue on `aiida-core` to flesh the idea out a bit more.

**Comment by danielhollas** [comment]
Thanks @sphuber! I've opened https://github.com/aiidateam/aiida-core/issues/5890 for further discussion.

@pzarabadip this PR is good to go.

**Review by ezpzbz — APPROVED** [review]

**Comment by ezpzbz** [comment]
Thanks @danielhollas. Merged.

**Pull request merged**
